spring:
  application:
    name: question-generator

  data:
    mongodb:
      uri: mongodb://localhost:27017/questionsdb

  aop:
    auto: false

server:
  port: 9097

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
